# Generated by Django 5.0.7 on 2024-08-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videopoker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hands_dealt',
            old_name='discarded',
            new_name='final',
        ),
        migrations.AddField(
            model_name='hands_dealt',
            name='win_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='balance',
            field=models.PositiveBigIntegerField(default=5000),
        ),
    ]
