# Generated by Django 3.2.18 on 2024-08-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videopoker', '0002_rename_discarded_hands_dealt_final_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hands_dealt',
            name='extra_cards',
        ),
        migrations.AlterField(
            model_name='hands_dealt',
            name='date_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
