# Generated by Django 5.0.7 on 2024-08-17 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videopoker', '0003_auto_20240813_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessfulPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(max_length=3)),
                ('total_amount', models.PositiveSmallIntegerField()),
                ('chips_bought', models.PositiveIntegerField()),
                ('telegram_id', models.PositiveBigIntegerField(blank=True)),
                ('telegram_payment_charge_id', models.CharField(max_length=512)),
                ('provider_payment_charge_id', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='All_Time_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hands_dealt', models.PositiveBigIntegerField()),
                ('amount_won', models.PositiveBigIntegerField()),
                ('royal_flush', models.PositiveIntegerField()),
                ('straight_flush', models.PositiveIntegerField()),
                ('four_of_kind', models.PositiveIntegerField()),
                ('full_house', models.PositiveIntegerField()),
                ('flush', models.PositiveIntegerField()),
                ('straight', models.PositiveIntegerField()),
                ('three_of_kind', models.PositiveIntegerField()),
                ('two_pairs', models.PositiveIntegerField()),
                ('jacks_or_better', models.PositiveBigIntegerField()),
                ('no_value_hand', models.PositiveBigIntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videopoker.users')),
            ],
        ),
    ]
