# Generated by Django 3.2.18 on 2024-08-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videopoker', '0004_successfulpayment_all_time_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
