# Generated by Django 5.0.7 on 2024-08-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videopoker', '0005_alter_users_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveBigIntegerField(blank=True)),
                ('suggestion', models.CharField(max_length=212)),
            ],
        ),
    ]
