# Generated by Django 3.2.18 on 2024-10-08 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videopoker', '0006_suggestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='adsgram_viewed_day',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='adsgram_views_today',
            field=models.SmallIntegerField(default=20),
        ),
    ]
