# Generated by Django 3.2.18 on 2024-11-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videopoker', '0007_auto_20241008_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinations',
            name='bronze',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combinations',
            name='gold',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combinations',
            name='platinum',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combinations',
            name='silver',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
