# Generated by Django 5.0.1 on 2024-02-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryDataETH',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
                ('close_time', models.DateTimeField()),
                ('quote_asset_volume', models.FloatField()),
                ('num_trades', models.PositiveIntegerField()),
                ('hour_sin', models.FloatField()),
                ('hour_cos', models.FloatField()),
                ('day_sin', models.FloatField()),
                ('day_cos', models.FloatField()),
                ('mon_sin', models.FloatField()),
                ('mon_cos', models.FloatField()),
                ('weekday_sin', models.FloatField()),
                ('weekday_cos', models.FloatField()),
                ('year', models.PositiveIntegerField()),
                ('RATIO_close_and_MA3', models.FloatField()),
                ('RATIO_close_and_MA6', models.FloatField()),
                ('RATIO_close_and_MA12', models.FloatField()),
                ('RATIO_close_and_MA24', models.FloatField()),
                ('RATIO_close_and_MA48', models.FloatField()),
                ('RATIO_close_and_MA96', models.FloatField()),
                ('RATIO_close_and_MA192', models.FloatField()),
                ('RATIO_close_and_MA384', models.FloatField()),
                ('RATIO_quote_asset_volume_and_MA3', models.FloatField()),
                ('RATIO_quote_asset_volume_and_MA6', models.FloatField()),
                ('RATIO_quote_asset_volume_and_MA12', models.FloatField()),
                ('RATIO_quote_asset_volume_and_MA24', models.FloatField()),
                ('RATIO_quote_asset_volume_and_MA48', models.FloatField()),
                ('RATIO_quote_asset_volume_and_MA96', models.FloatField()),
                ('RATIO_quote_asset_volume_and_MA192', models.FloatField()),
                ('RATIO_quote_asset_volume_and_MA384', models.FloatField()),
                ('RATIO_num_trades_and_MA3', models.FloatField()),
                ('RATIO_num_trades_and_MA6', models.FloatField()),
                ('RATIO_num_trades_and_MA12', models.FloatField()),
                ('RATIO_num_trades_and_MA24', models.FloatField()),
                ('RATIO_num_trades_and_MA48', models.FloatField()),
                ('RATIO_num_trades_and_MA96', models.FloatField()),
                ('RATIO_num_trades_and_MA192', models.FloatField()),
                ('RATIO_num_trades_and_MA384', models.FloatField()),
                ('RATIO_close_and_STD3', models.FloatField()),
                ('RATIO_close_and_STD6', models.FloatField()),
                ('RATIO_close_and_STD12', models.FloatField()),
                ('RATIO_close_and_STD24', models.FloatField()),
                ('RATIO_close_and_STD48', models.FloatField()),
                ('RATIO_close_and_STD96', models.FloatField()),
                ('RATIO_close_and_STD192', models.FloatField()),
                ('RATIO_close_and_STD384', models.FloatField()),
                ('RSI_3_close', models.FloatField()),
                ('RSI_6_close', models.FloatField()),
                ('RSI_12_close', models.FloatField()),
                ('RSI_24_close', models.FloatField()),
                ('RSI_48_close', models.FloatField()),
                ('RSI_96_close', models.FloatField()),
                ('RSI_192_close', models.FloatField()),
                ('RSI_384_close', models.FloatField()),
            ],
        ),
    ]
